--- #YAML:1.0
name:               Crypt-OpenSSL-Cloner
version:            0.02
abstract:           Clone an existing certificate and sign it with your own
author:
    - M. Nunberg <mnunberg@haskalah.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Convert::ASN1:        0
    Crypt::OpenSSL::CA:   0
    Crypt::OpenSSL::RSA:  0
    File::Slurp:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
